baseURL: http://justsaynotosalad.com
disablePathToLower: true
languageCode: en-us
title: Just Say No!
theme: gochowdown
googleAnalytics:
defaultcontentlanguage: en
paginate: 20
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: James Spargo & Micheal Pitre
  description: Recipes that aren't salads
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent: 
  hidecredits: true
  hidecopyright: false
menu:
  main:
    - name: Home
      weight: 1
      url: /
#    - name: Category
#      weight: 2
#      url: /category/
#    - name: Cuisine
#      weight: 3
#      url: /cuisine/
#    - name: Tags
#      weight: 4
#      url: /tags/
taxonomies:
  category: category
  cusine: cuisine
  tag: tags

